### ISSUE TITLE
Add padding to email-recs to offset the case of it being in a grid

### ISSUE THREAD

**Issue by pineapplegiant** [searchspring/snapfu-scaffold-preact-email#12]
It's difficult to test how the email recommendations looks likes in the imager, however in order to style it appropriately the styles have to be baked into the component. Currently in the default component there's a [style with hardcoded widths added inline](https://github.com/searchspring/snapfu-template-preact-email/blob/17150d08cf6de6333afaef52a726baf04db041bc/src/components/Recommendations/Email.jsx#L36), so that the email component is captured properly in the imager. I propose adding some padding here as well so that the default view isn't so smushed in the case of the email template being placed in a grid. Perhaps 5 or 10px or something?

So this line should change from:
```jsx
<div key={idx} id={`ss-emailrec${idx}`} style={{ display: 'block', width: '240px' }}>
```

To:
```jsx
<div key={idx} id={`ss-emailrec${idx}`} style={{ display: 'block', width: '240px', padding: '10px' }}>
```

Probably could also refactor if we wanted to a style variable object or all the things on there.

const `emailStyles = { display: 'block', width: '240px', padding: '10px' }` and then spread it or whatever seems neat.

**Comment by korgon** [comment]
This is a per-site preference, so the padding can be altered as needed, when needed.
